server:
  port: 8081

spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  # API 실행을 통해 실제 데이터를 확인하기 위한 코드
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true